# Generated by Django 6.0 on 2026-01-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
